Refactor reservations
maciejfedor/monte-cinema pull request #15
Opened 2022-10-03 09:49 UTC by maciejfedor

2022-10-03 20:24 UTC, Protoplaste requested changes

2022-10-03 20:24 UTC, Protoplaste commented on app/validators/seats_validator.rb
> +    return false if seats.blank?
Validations should return errors for error handling or nothing if it passes, not true or false
```suggestion
    errors.add(:seat, :cannot_be_blank) and return if seats.blank?
```

2022-10-03 20:24 UTC, Protoplaste commented on app/models/ticket.rb
> -  end
This should be replaced with a call to the validator class you created

2022-10-03 20:24 UTC, Protoplaste commented on spec/factories/reservation.rb
> +    screening_id {1}
that won't work unless there is a screening already in the database, and every spec starts with empty db
```suggestion
    screening
```
This will look for a screening factory and create a screening for you

2022-10-03 20:24 UTC, Protoplaste commented on spec/factories/reservation.rb
> +    status {0}
I would use status names rather than numbers

2022-10-03 20:24 UTC, Protoplaste commented on spec/factories/screening.rb
> +    hall_id { 1 }
Never hardcode record id's, this will break
```suggestion
    movie
    hall
```

2022-10-03 20:24 UTC, Protoplaste commented on spec/factories/user.rb
> +    email { 'user@example.com' }
Consider using a Faker gem
This will allow you to generate random email addresses and other data you might need
Will be useful here as email addresses usually need to be unique so this would only allow you to generate one user per spec

2022-10-03 20:24 UTC, Protoplaste commented on spec/use_cases/reservations/cancel_spec.rb
> +    let(:seats) { [10, 11, 12, 13] }
you can generate array of a sequence of numbers like so:
```suggestion
    let(:seats) { [*10..13] }
```

2022-10-03 20:24 UTC, Protoplaste commented on spec/use_cases/reservations/cancel_spec.rb
> +    let(:screening) { create(:screening, hall_id: hall.id, movie_id: movie.id, start_time: Date.current + 2.days) }
do not assign id's, assign objects, it's much cleaner
```suggestion
    let(:screening) { create(:screening, hall:, movie:, start_time: Date.current + 2.days) }
```

2022-10-03 20:24 UTC, Protoplaste commented on spec/use_cases/reservations/cancel_spec.rb
> +    let(:screening) { create(:screening, hall_id: hall.id, movie_id: movie.id, start_time: Date.current + 2.days) }
same in other let's and other spec files

2022-10-03 20:24 UTC, Protoplaste commented on spec/use_cases/reservations/cancel_spec.rb
> +  end
```suggestion
    let(:params) do 
      { id: reservation.id }
    end
```

2022-10-03 20:24 UTC, Protoplaste commented on spec/use_cases/reservations/create_at_desk_spec.rb
> +      end
If you just need to change what seats are in this hash you can overwrite the seats param
This will change the params hash defined at the top as it will use the seats definition from the nested context
```suggestion
      let(:seats) { [] }
```

2022-10-03 20:24 UTC, Protoplaste commented on spec/use_cases/reservations/update_spec.rb
> +    let(:user) { create(:user) }
You are not using these, remove them to avoid confusion

2022-10-03 20:29 UTC, Protoplaste requested changes

2022-10-03 20:39 UTC, Protoplaste reviewed
I honestly think all those UseCase's are a massive overkill
For them to be justified this would have to be a very complex application, then they might be useful to manage that complexity
But patterns for managing complexity add complexity of themselves so when you apply them to problems that are not that complex you are just adding complexity for no reason
I would revert the changes related to UseCase's, the previous version of reservations controller was much more readable
Unless this was a requirement, then my point still stands, but carry on :)

2022-10-04 14:31 UTC, maciejfedor commented
@Protoplaste , I think I've implemented all suggested changes regarding tests. When it comes to seats validation, I restored validation in the model so there is a validation on model level, but I used that custom seats_validator in a different way, in a use case. I'm aware those use cases are making it too complex, but I just wanted to practice the approach we were taught on at least one controller and because of that I decided to leave it as it is.

2022-10-05 04:21 UTC, Protoplaste requested changes

2022-10-05 04:25 UTC, Protoplaste commented on app/concepts/reservations/use_cases/create_at_desk.rb
> +      end
This should also create reservation with it's tickets in a single transaction 
So it will rollback creating reservation if something goes wrong with creating tickets

2022-10-05 11:28 UTC, merged