Add cancel reservations job
maciejfedor/monte-cinema pull request #17
Opened 2022-10-05 13:49 UTC by maciejfedor

I've added cron job responsible for canceling all reservations that have not been confirmed till 30 minutes before screening start time.

- added sidekiq and sidekiq-cron gems
- added sidekiq config file
- added cancel pending reservations job
- changed time zone
- added schedule.yml and set interval to 5 minutes

2022-10-05 14:56 UTC, h4ppyr0gu3 commented on app/concepts/reservations/use_cases/create.rb
>        def initialize(screening_id:, user_id:, seats:, status:, repository: ReservationRepository.new)
repository should probably be a method instead of a parameter passed to initialize

2022-10-05 20:36 UTC, kodowicz requested changes

2022-10-05 20:36 UTC, kodowicz commented on app/jobs/cancel_pending_reservations_job.rb
> +  def perform(*_args)
```suggestion
  def perform
```

2022-10-05 20:36 UTC, kodowicz commented on app/jobs/cancel_pending_reservations_job.rb
> +      @reservation = reservation
why instance variable in a iteration? It doesn't make sense to override value on this variable with every iteration

2022-10-05 20:36 UTC, kodowicz commented on config/schedule.yml
> +  queue: default
I'll paste what I said in Monika's PR:

> Why do you want to create a cron job instead of calling a job and scheduling it to 30 minutes? In this case, it could be a situation when the cron job was performed 1 minute ago and now I'm buying a ticket so it will be checked when the ticket was created 29 minutes ago and next time when it was created 34 minutes ago. The ticket should have been canceled for 4 minutes.

> Definitely a better solution is to schedule a job for 30minutes when a reservation has been created.

2022-10-05 20:36 UTC, kodowicz commented on spec/use_cases/reservations/cancel_spec.rb
> +                                         status: :booked).call
we never create variables like that :D You don't now if using this use case doesn't create any errors. You definitely should use factory bot like before. Looking at your new factory it could be simply 
```suggestion
let(:reservation) { create(:reservation) }
```

2022-10-05 20:36 UTC, kodowicz commented on spec/use_cases/reservations/cancel_spec.rb
> +    let(:cancel_reservation) { described_class.new(**params).call }
you don't need `**` operator :) 
```suggestion
    let(:cancel_reservation) { described_class.new(params).call }
```

2022-10-05 20:57 UTC, maciejfedor commented on Gemfile
> +gem 'sidekiq', '~> 6.5', '>= 6.5.7'
With no particular reason to be honest, i copied that from rubygems, didn't know it is something you shouldn't do, but i have that strict version restrictions also in other, even automatically generated gems. Should I remove it from all gems that have this specified ?

2022-10-05 20:59 UTC, baniak66 commented on app/concepts/reservations/use_cases/create.rb
>        def initialize(screening_id:, user_id:, seats:, status:, repository: ReservationRepository.new)
Or maybe it's better to delete the `repository`... it's not used anywhere.

2022-10-05 21:52 UTC, maciejfedor commented on app/jobs/cancel_pending_reservations_job.rb
> +  def perform(*_args)
It doesn't work without that, I'm not sure why. I'm getting that error `ArgumentError (wrong number of arguments (given 0, expected 1))`

2022-10-05 23:18 UTC, maciejfedor commented on app/concepts/reservations/use_cases/create.rb
>        def initialize(screening_id:, user_id:, seats:, status:, repository: ReservationRepository.new)
That's right, i didin't noticed I'm not using it after changes

2022-10-05 23:19 UTC, maciejfedor commented on spec/jobs/cancel_pending_reservations_job_spec.rb
> +end
I've added tests

2022-10-05 23:22 UTC, maciejfedor commented on spec/use_cases/reservations/cancel_spec.rb
> +    let(:cancel_reservation) { described_class.new(**params).call }
Actually it does not work without that double splat operator. i get that error `ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: id)`

2022-10-05 23:23 UTC, maciejfedor commented on app/jobs/cancel_pending_reservations_job.rb
> +      cancel_reservation if after_deadline?
I changed it as suggested

2022-10-05 23:31 UTC, maciejfedor commented on spec/use_cases/reservations/cancel_spec.rb
> +                                         status: :booked).call
i changed a way of validating reservation model. I'm validating it after creating tickets for it so factory wasn't working anymore because it raised an active record error connected to seats not being chosen and reservation itself does not hold information about seats. I used that use case as a not so elegant workaround but now I changed factory for reservation and I hope it makes sense and is acceptable.

2022-10-05 23:32 UTC, maciejfedor commented on spec/use_cases/reservations/cancel_spec.rb
> +                                         status: :booked).call
i changed a way of validating reservation model. I'm validating it after creating tickets for it so factory wasn't working anymore because it raised an active record error connected to seats not being chosen and reservation itself does not hold information about seats. I used that use case as a not so elegant workaround but now I changed factory for reservation and I hope it makes sense and is acceptable.

2022-10-05 23:42 UTC, maciejfedor commented on spec/use_cases/reservations/update_spec.rb
> +    let(:update_reservation) { described_class.new(**params).call }
To be honest I'm not too sure, i had problems with test and thought it's connected to that somehow, i overlooked it, will change to subject again.

2022-10-06 06:09 UTC, h4ppyr0gu3 commented on Gemfile
> +gem 'sidekiq', '~> 6.5', '>= 6.5.7'
i guess it is fine i guess just could be misleading

2022-10-06 06:10 UTC, baniak66 commented on spec/jobs/cancel_pending_reservations_job_spec.rb
> +RSpec.describe CancelPendingReservationsJob, type: :job do
Tests for job 👏

2022-10-06 06:10 UTC, baniak66 commented on spec/factories/reservation.rb
> +    end
I think you can use `after(:create)` callback here instead of bypassing validations. https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#has_many-associations

2022-10-06 06:56 UTC, kodowicz commented on spec/use_cases/reservations/cancel_spec.rb
> +    let(:cancel_reservation) { described_class.new(**params).call }
ok because the initializer looks like this:
```ruby
def initialize(id:, repository: ReservationRepository.new)
```

So you should pass arguments like this:
```ruby
let(:cancel_reservation) { described_class.new(id: id).call }
```
Another thing is that your usecase doesn't care about params so you can just define id variable
```ruby
let(:id) { reservation.id }
```

2022-10-06 07:54 UTC, maciejfedor commented on spec/factories/reservation.rb
> +    end
If I'm not mistaken, that also wouldn't work.

Validation for reservation model looks like this:

```
  def validate_reservation
    seats = tickets.map(&:seat)
    errors.add(:base, message: 'Choose at least one seat') if seats.blank?
    errors.add(:base, message: 'Seat(s) taken') if !seats.blank? && seat_taken?(screening, seats)
  end
```
And the call method that creates reservation like that:

```
      def call
        screening
        reservation = Reservation.new(screening:, user_id:, status: :booked)
        seats.each { |seat| reservation.tickets.new(seat:) } if seats.present?
        reservation.save
        reservation
      end
```
So i think I cannot use `after(:create)` in that case because `reservation.save` takes place with tickets already being added, i save everything at once. Is it ok then to omit that validation in udpate tests, or should I do it some other way ?

2022-10-06 08:53 UTC, maciejfedor commented on spec/factories/reservation.rb
> +    end
I used different solution for that: 
```    
let(:ticket) { build(:ticket, seat: '1') }
let(:reservation) { create(:reservation, tickets: [ticket]) }
```

2022-10-06 10:13 UTC, merged

2022-10-06 10:25 UTC, baniak66 commented on spec/factories/reservation.rb
> +    end
Much better 👍